platform :ios, '7.0'

pod 'CocoaLumberjack'
pod 'FMDB'
#pod 'NSJSONSerialization-NSNullRemoval', '~> 1.0.0'
#pod 'JSONKit', '~> 1.5pre'
pod 'AFNetworking', '~> 2.4.1'
#pod 'MBProgressHUD', '~> 0.9'
#pod 'XMPPFramework', '~> 3.6.4'
#pod 'MagicalRecord', '~> 2.2'
#pod 'ReactiveCocoa', '~> 2.3.1'
#pod 'RBStoryboardLink', '~> 0.1.0'
#pod 'SVPullToRefresh', '~> 0.4.1'
#pod 'NMRangeSlider', '~> 1.2.1'
